### ISSUE TITLE
"inject -s" syntax doesn't match "build -s" syntax

### ISSUE THREAD

**Issue by kevlar1818** [InspectorMustache/base16-builder-python#13]
`inject -s` expects a real path to a scheme file, while `build -s` just takes a scheme name. Ideally the two interfaces should be consistent (and subsequently `build -t` would also be consistent).

**Comment by InspectorMustache** [comment]
Yeah, good point. I'm not sure why I didn't set it up like that from the beginning but to be honest with you the codebase isn't really what one would call clean. Anyway, the `-s` flag for inject shuld now work identically to build. Give it a try and let me know what you think.

For the template flag, I'm gonna stay with folder names as that seems much more practical to me. The  different files in the template folders are subtemplates and their names are usually not very transparent (every template has a "default" subtemplate/file).

**Comment by kevlar1818** [comment]
Is this changed pushed to the PyPI? When I try this I get an exception:
```
$ poetry run pybase16 inject -s phd -f ~/.Xresources.d/pybase16
Traceback (most recent call last):
  File "/home/kevin/.cache/pypoetry/virtualenvs/pybase16-py3.7/bin/pybase16", line 10, in <module>
    sys.exit(run())
  File "/home/kevin/.cache/pypoetry/virtualenvs/pybase16-py3.7/lib/python3.7/site-packages/pybase16_builder/cli.py", line 115, in run
    inject_mode(arg_namespace)
  File "/home/kevin/.cache/pypoetry/virtualenvs/pybase16-py3.7/lib/python3.7/site-packages/pybase16_builder/cli.py", line 87, in inject_mode
    arg_namespace.file)
  File "/home/kevin/.cache/pypoetry/virtualenvs/pybase16-py3.7/lib/python3.7/site-packages/pybase16_builder/injector.py", line 99, in inject_into_files
    colorscheme = rec.get_colorscheme(scheme_file)
  File "/home/kevin/.cache/pypoetry/virtualenvs/pybase16-py3.7/lib/python3.7/site-packages/pybase16_builder/injector.py", line 47, in get_colorscheme
    builder.format_scheme(scheme, scheme_slug)
  File "/home/kevin/.cache/pypoetry/virtualenvs/pybase16-py3.7/lib/python3.7/site-packages/pybase16_builder/builder.py", line 88, in format_scheme
    scheme['scheme-name'] = scheme.pop('scheme')
KeyError: 'scheme'
```

**Comment by InspectorMustache** [comment]
No, this is just the latest commit on master.

**Comment by InspectorMustache** [comment]
Alright, good enough I guess, I pushed the update to PyPI.

**Comment by InspectorMustache** [comment]
I'm closing this now. Let me know if you're still having problems.
